// // app/layout.js
// import './globals.css';
// import 'bootstrap/dist/css/bootstrap.min.css';
// import BootstrapProvider from './BootstrapProvider';
// import { Poppins } from 'next/font/google';
// import Layout from '@/components/layout/page'; // Assuming this is your custom layout component
// import { Toaster } from 'react-hot-toast';
// import ThemeProviderWrapper from './ThemeProviderWrapper'; // Import the wrapper
// import { Provider } from 'react-redux';
// import { store } from '../app/redux/redux';

// const poppins = Poppins({
//   subsets: ['latin'],
//   weight: ['400', '500', '600', '700'],
//   variable: '--font-poppins',
//   display: 'swap',
// });

// export const metadata = {
//   title: 'Momee Adminpanel',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body style={{ fontFamily: 'Poppins' }} className={poppins.variable}>
//       <Provider store={store}>
//       <BootstrapProvider /> 
//         <Layout>
//           <Toaster
//             toastOptions={{
//               style: {
//                 fontSize: '16px',
//                 padding: '12px 20px',
//                 background: '#333',
//                 color: '#fff',
//                 borderRadius: '8px',
//               },
//               success: {
//                 style: {
//                   background: '#4BB543',
//                 },
//               },
//               error: {
//                 style: {
//                   background: '#FF3333',
//                 },
//               },
//             }}
//           />
//           <ThemeProviderWrapper>{children}</ThemeProviderWrapper>
//         </Layout>
//         </Provider>
//       </body>
//     </html>
//   );


// }

// app/layout.js (or layout.tsx)

import './globals.css';
import '../styles/fonts.css';
import ClientLayoutWrapper from './layout-provider';
import 'leaflet/dist/leaflet.css';

export const metadata = {
  title: 'Momee Adminpanel',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: 'Poppins, sans-serif' }}>
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}
